POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "the fk",
    "important": true
}
###
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "?",
    "sth": "sth"

}
###
DELETE http://localhost:3001/api/notes/66c5b02d4fa2c0401a34bf14

