POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "may be id will be num 4",
    "important": true
}
###
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "sample",
    "sth": "sth"

}
